### ISSUE TITLE
Replies to your Nim question

### ISSUE THREAD

**Issue by mratsim** [timotheecour/D_vs_nim#10]
Hello there,

Here is a reply to your Nim questions

## Questions

1. how to specify immutable inside for(foo in bar) ?
2. does it have dfmt equivalent?
3. has REPL?
4. can we modify a slice of an immutable array declared by 'let'?
5. how to use global variables? (cf http://gradha.github.io/articles/2015/02/goodbye-nim-and-good-luck.html)
6. rdmd equivalent?
7. how to search for symbols fooBar given that nim allows foobar fooBar foo_bar etc?

## Answers

- [x] 1. Immutability is defined by the iterator return type.
`for foo in in bar` implicitely calls the `items` iterator which is defined as `iterator items[T](a: yourCollection[T]): T =` meaning it accepts a collection and return an immutable value.

The mutable iterator is `iterator mitems[T](a: var yourCollection[T]): var T =` and you call it like that `for foo in bar.mitems:`

- [x] 2. No

- [x] 3. unofficially, you can use `nim secret` but it does not support a lot of things. The most promising is [nrpl](https://github.com/wheineman/nrpl).

- [x] 4. Slicing doesn't return a var T for `let` arrays so you can't. Note that immutability for stack objects/array/types is deep but for ref/ptr types it is shallow, it means that the memory address pointed to cannot be modified but the content can.

- [x] 5. I don't understand the issue. Non-const global vars are not allowed in proc tagged `noSideEffects` and care must be used if accessed from multiple threads but there is nothing special about them otherwise.

- [x] 6. Not sure about how D compilation works and why this is needed. Nim only compiles changed file by default.

- [x] 7. Nim provides "nimsuggest" that can be used for vim, emacs, vscode, atom that autocompletes. Otherwise, consistency within a library.

**Comment by timotheecour** [comment]
thanks! incorporating your answers gradually in the README (eg https://github.com/timotheecour/D_vs_nim/commit/d29221cc593fa09475516d7d4897bd72257dd2fd) and marking these as checked in ur answer
