### ISSUE TITLE
Some small remarks

### ISSUE THREAD

**Issue by dom96** [timotheecour/D_vs_nim#18]
> no heap-allocated runtime type at compile-time. 

This is misleading, see IRC logs: https://irclogs.nim-lang.org/27-03-2018.html#13:40:09

> markdown

Nim uses reStructuredText for documentation, not markdown.

> WYSIWYG string

Probably ``r"foo\nbar"`` is more appropriate (and Python-like!). The ``"""..."""`` works too but is more commonly used for multi-line strings.

**Comment by timotheecour** [comment]
thanks!

@dom96 fixed via 4227705dc9169061d1ce645c9c57c28995daf6bc and 8045fb91eea22b87b2cd336aeffa1709539d4a97

> This is misleading, see IRC logs: https://irclogs.nim-lang.org/27-03-2018.html#13:40:09

indeed, allocation at CTFE works, I corrected the readme

```nim
proc testCTFE2():auto=
    var a=""
    for i in 0..10:
        a &= " " & $(100+i)
    var numNodes=a.len
    var c:ref Node
    c.new
    var b = newSeq[bool](numNodes)
    a &= $(b)
    return a

const temp=testCTFE2()
```

**Comment by dom96** [comment]
Great, btw you can get Nim syntax highlighting on GitHub using \```nim ... \```

**Comment by timotheecour** [comment]
thx, fixed :)
