### ISSUE TITLE
About package modules

### ISSUE THREAD

**Issue by ghost** [timotheecour/D_vs_nim#22]
In nim you can just use export/import together to achieve the same, for example main .nim file from Arraymancer, and then you can just use "import arraymancer" and it's done (and you can import different files (packages?) from subfolders too
https://github.com/mratsim/Arraymancer/blob/master/src/arraymancer.nim

**Comment by timotheecour** [comment]
in D:
```
#before:
std/foo.d
#after breakup:
std/foo/package.d
std/foo/mod1.d
std/foo/mod2.d
```
in Nim:
```
#before:
std/foo.nim
#after breakup:
std/foo.nim
std/foo/mod1.d
std/foo/mod2.d
```

so it's not quite as clean as in D because `std/foo.nim` remains on top-level instead of all the foo stuff being inside `foo/`

Admittedly, it's not that huge of a difference

**Comment by marler8997** [comment]
I think I actually prefer Nims solution here :)

**Comment by marler8997** [comment]
But...Nim's solution is a subset of D's.  You can do the same thing in D.  It's just that D also supports more functionality, which in my opinion doesn't add much value while adding complexity to the module system.

**Comment by timotheecour** [comment]
right, definitely not a big point; i mentioned this issue in the readme for reference, closing
