### ISSUE TITLE
Number of packages in Nimble

### ISSUE THREAD

**Issue by ghost** [timotheecour/D_vs_nim#3]
If you check  [nimble package repository](https://github.com/nim-lang/packages) where package.json is stored, you can actually see that there's 639 packages, not 194 (I don't know where did you take that number from)

**Comment by timotheecour** [comment]
@Yardanico thanks the input; will pull your PR soon; I got the number from:
https://nimble.directory/packages.xml which shows 194 pacakges
is that file outdated? should it be updated?

will close this issue after your reply

**Comment by ghost** [comment]
@timotheecour this list seem to contain only packages which were added after nimble.directory got created (maybe?) `New and updated Nim packages` - so no old packages

**Comment by timotheecour** [comment]
gotcha, I missed that; I'm pretty sure I'm not the only one who'll get confused by that; it's made worse by the fact that https://github.com/nim-lang/Nim/issues/7400 still prevents someone browsing https://nim-lang.org/docs/lib.html from seeing packages, the fact that https://nimble.directory/ doesn't show the total number of packages.

opened https://github.com/nim-lang/Nim/issues/7410 just in case
