### ISSUE TITLE
Bias in counting features 

### ISSUE THREAD

**Issue by Laeeth** [timotheecour/D_vs_nim#32]
It's reasonable to have a point of view, but you will be taken more seriously if you make it explicit.  D can't write to file system at compile time as a deliberate choice and one reason for that is to make it suitable for use on an industrial scale.  Its okay to disagree with that choice but you ought to make clear its an opinionated assessment and not striving to be objective.  Different people may reasonably agree about it.  As an enterprise user of D I see the absence of this feature as a positive, but you deduct points for it.  I'm not averse to also using Nim BTW, but D is pushing it and I didn't think Nim was ready yet.

**Comment by timotheecour** [comment]
I'm trying to be as objective as possible, but for some features, opinion/objectivity is a gray area (just needs a bit more in rationale section for those cases)
as for your specific point: `D can't write to file system at compile time as a deliberate choice and one reason for that is to make it suitable for use on an industrial scale`:
I have to disagree: it's trivial in Nim to disable this feature: just patch the standard library in system.nim to disable `gorgeEx` + friends: it's just a 1 line patch:
`when not defined(nimDisallowWriteCT) ...`
(alternatively, disable that feature in the compiler itself in the magic that defines `gorgeEx`)
so a company could decide to disable this feature for their builds.

Whereas the reverse doesn't hold: it's not trivial to add this feature in D (ditto with the other things you can do in Nim at compile time, such as call arbitrary C functions)
